// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SquareHinge
Rcpp::List SquareHinge(arma::mat& YMAT, int DIM, double EPSILON, bool returnAll, double rho);
RcppExport SEXP _SSOSVM_SquareHinge(SEXP YMATSEXP, SEXP DIMSEXP, SEXP EPSILONSEXP, SEXP returnAllSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type YMAT(YMATSEXP);
    Rcpp::traits::input_parameter< int >::type DIM(DIMSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON(EPSILONSEXP);
    Rcpp::traits::input_parameter< bool >::type returnAll(returnAllSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(SquareHinge(YMAT, DIM, EPSILON, returnAll, rho));
    return rcpp_result_gen;
END_RCPP
}
// Hinge
Rcpp::List Hinge(arma::mat& YMAT, int DIM, double EPSILON, bool returnAll, double rho);
RcppExport SEXP _SSOSVM_Hinge(SEXP YMATSEXP, SEXP DIMSEXP, SEXP EPSILONSEXP, SEXP returnAllSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type YMAT(YMATSEXP);
    Rcpp::traits::input_parameter< int >::type DIM(DIMSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON(EPSILONSEXP);
    Rcpp::traits::input_parameter< bool >::type returnAll(returnAllSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Hinge(YMAT, DIM, EPSILON, returnAll, rho));
    return rcpp_result_gen;
END_RCPP
}
// Logistic
Rcpp::List Logistic(arma::mat& YMAT, int DIM, double EPSILON, bool returnAll, double rho);
RcppExport SEXP _SSOSVM_Logistic(SEXP YMATSEXP, SEXP DIMSEXP, SEXP EPSILONSEXP, SEXP returnAllSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type YMAT(YMATSEXP);
    Rcpp::traits::input_parameter< int >::type DIM(DIMSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON(EPSILONSEXP);
    Rcpp::traits::input_parameter< bool >::type returnAll(returnAllSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Logistic(YMAT, DIM, EPSILON, returnAll, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSOSVM_SquareHinge", (DL_FUNC) &_SSOSVM_SquareHinge, 5},
    {"_SSOSVM_Hinge", (DL_FUNC) &_SSOSVM_Hinge, 5},
    {"_SSOSVM_Logistic", (DL_FUNC) &_SSOSVM_Logistic, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSOSVM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
